# This is a basic workflow to help you get started with Actions

name: Build test for MaixCAM2

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# permissions: write-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Only run job for specific repository
    if: github.repository == 'sipeed/MaixCDK'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"] # MaixCAM2 use 3.13
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build MaixCDK Examples
        run: |
          echo "-- Check python version must python 3.13 --"
          python3 -c 'import sys;print(sys.version);assert sys.version_info >= (3, 13);assert sys.version_info < (3, 14)'
          python -c 'import sys;print(sys.version);assert sys.version_info >= (3, 13);assert sys.version_info < (3, 14)'
          whereis python
          whereis python3
          # export PATH=~/.local/bin/:$PATH
          echo "--------------------------------"
          echo "-- Install requirements first --"
          echo "--------------------------------"
          python -m pip install -r requirements.txt
          sudo apt update -y
          sudo apt install -y cmake autoconf automake libtool git build-essential
          echo "--------------------------------"
          echo "-- Build Test for MaixCAM2 now --"
          echo "--------------------------------"
          cd test/test_examples
          chmod +x test_cases.sh
          ./test_cases.sh maixcam2 0
          echo "------------------------------------"
          echo "-- Build Projects for MaixCAM2 now --"
          echo "------------------------------------"
          cd ../../projects
          chmod +x build_all.sh
          ./build_all.sh maixcam2

      - name: Build doc
        run: |
          pip3 install teedoc
          cd docs
          echo "== install plugins =="
          teedoc install
          echo "== start build =="
          teedoc build
          echo "== build complete =="
